import path from "path";

import type { DirToProcessProps, OutputFileProps } from "@/types/globals";

// The root directory containing content files
const contentDirectory: string = path.join(process.cwd(), "content");

// The directory where generated output files are stored
const dataDirectory: string = path.join(process.cwd(), "content", "data", "__generated__");

// Filenames for generated output files
const outputFiles: OutputFileProps = {
  contentTreeOutput: "content-tree.ts",
  shortlinkOutput: "shortlinks.ts",
};

// List of directories to process, with associated processing options
const dirsToProcess: DirToProcessProps[] = [
  {
    path: path.join(contentDirectory, "topics"),
    options: {
      addToContentTree: true,
      generateShortlink: true,
      generateTableOfContents: true,
    },
  },
  {
    path: path.join(contentDirectory), // Main pages
    options: {
      addToContentTree: false,
      generateShortlink: false,
      generateTableOfContents: true,
    },
  },
];

const autogeneratedComment = "// This file is auto-generated";

export { contentDirectory, dataDirectory, outputFiles, dirsToProcess, autogeneratedComment };
