import type { Globals } from "@/types/globals";

export interface TopicLinkProps extends Globals.LinkProps {
  subtopics: {
    key: string;
    title: string;
    path: string;
    articles: Globals.LinkProps[];
  }[];
}

/**
 * These are placeholder topics generated by AI. Most of them can be removed in the future
 */
export const topicLinks: TopicLinkProps[] = [
  {
    key: "koloniyalizm",
    title: "Koloniyalizm",
    path: "/koloniyalizm",
    subtopics: [
      {
        key: "kesif-cagi",
        title: "Keşif Çağı",
        path: "/konular/kesif-cagi",
        articles: [
          {
            key: "portekiz-kesifleri",
            title: "Portekiz Keşifleri",
            path: "/makaleler/portekiz-kesifleri",
          },
          {
            key: "ispanyol-kesifleri",
            title: "İspanyol Keşifleri",
            path: "/makaleler/ispanyol-kesifleri",
          },
          {
            key: "afrika-kiyilari",
            title: "Afrika Kıyılarında Keşifler",
            path: "/makaleler/afrika-kiyilari",
          },
          {
            key: "hint-denizi",
            title: "Hint Denizi Ticaret Yolları",
            path: "/makaleler/hint-denizi",
          },
          {
            key: "dunyayi-kesfetmek",
            title: "Dünyayı Keşfetmek",
            path: "/makaleler/dunyayi-kesfetmek",
          },
          {
            key: "pusulanin-etkisi",
            title: "Pusulanın Keşiflere Etkisi",
            path: "/makaleler/pusulanin-etkisi",
          },
          {
            key: "haritalar",
            title: "Haritaların Gelişimi",
            path: "/makaleler/haritalar",
          },
          {
            key: "maceracilar",
            title: "Maceracılar ve Kâşifler",
            path: "/makaleler/maceracilar",
          },
          {
            key: "denizcilik-teknolojileri",
            title: "Denizcilik Teknolojilerindeki Gelişmeler",
            path: "/makaleler/denizcilik-teknolojileri",
          },
          {
            key: "kolonicilik-ve-kesif",
            title: "Kolonicilik ve Keşif Arasındaki Bağlantı",
            path: "/makaleler/kolonicilik-ve-kesif",
          },
        ],
      },
      {
        key: "amerikada-kolonicilik",
        title: "Amerika'da Kolonicilik",
        path: "/konular/amerikada-kolonicilik",
        articles: [
          {
            key: "ispanyol-somurgeleri",
            title: "İspanyol Sömürgeleri",
            path: "/makaleler/ispanyol-somurgeleri",
          },
          {
            key: "ingiliz-kolonileri",
            title: "İngiliz Kolonileri",
            path: "/makaleler/ingiliz-kolonileri",
          },
          {
            key: "yerli-halklar",
            title: "Yerli Halklarla İlk Temaslar",
            path: "/makaleler/yerli-halklar",
          },
          {
            key: "serflik-ve-kolelik",
            title: "Serflik ve Kölelik Sistemi",
            path: "/makaleler/serflik-ve-kolelik",
          },
          {
            key: "bağımsızlık-savaşları",
            title: "Bağımsızlık Savaşları",
            path: "/makaleler/bagimsizlik-savaslari",
          },
          {
            key: "tutun-ve-seker",
            title: "Tütün ve Şeker Üretimi",
            path: "/makaleler/tutun-ve-seker",
          },
          {
            key: "maden-somurgeleri",
            title: "Maden Sömürgeleri",
            path: "/makaleler/maden-somurgeleri",
          },
          {
            key: "misyonerlik-faaliyetleri",
            title: "Misyonerlik Faaliyetleri",
            path: "/makaleler/misyonerlik-faaliyetleri",
          },
          {
            key: "fransiz-ve-hollandali-koloniler",
            title: "Fransız ve Hollandalı Koloniler",
            path: "/makaleler/fransiz-ve-hollandali-koloniler",
          },
          {
            key: "amerika-ekonomik-yapi",
            title: "Kolonilerin Ekonomik Yapısı",
            path: "/makaleler/amerika-ekonomik-yapi",
          },
        ],
      },
      {
        key: "asyada-kolonicilik",
        title: "Asya'da Kolonicilik",
        path: "/konular/asyada-kolonicilik",
        articles: [
          {
            key: "hint-yarimadasi",
            title: "Hint Yarımadasında İngiliz Hakimiyeti",
            path: "/makaleler/hint-yarimadasi",
          },
          {
            key: "cin-ve-afyon-savaslari",
            title: "Çin ve Afyon Savaşları",
            path: "/makaleler/cin-ve-afyon-savaslari",
          },
          {
            key: "japonya-ve-izolasyon",
            title: "Japonya'nın İzolasyon Politikası",
            path: "/makaleler/japonya-ve-izolasyon",
          },
          {
            key: "rusyanin-genislemesi",
            title: "Rusya’nın Asya’daki Genişlemesi",
            path: "/makaleler/rusyanin-genislemesi",
          },
          {
            key: "ticaret-limanlari",
            title: "Ticaret Limanlarının Önemi",
            path: "/makaleler/ticaret-limanlari",
          },
          {
            key: "bati-ve-asya",
            title: "Batı'nın Asya'ya Etkisi",
            path: "/makaleler/bati-ve-asya",
          },
          {
            key: "somurgeci-ordular",
            title: "Sömürgeci Ordular ve Direnişler",
            path: "/makaleler/somurgeci-ordular",
          },
          {
            key: "endonezya-ve-hollandali-somurgecilik",
            title: "Endonezya ve Hollanda Sömürgeciliği",
            path: "/makaleler/endonezya-ve-hollandali-somurgecilik",
          },
          {
            key: "fransiz-hakimiyeti",
            title: "Fransızların Asya'daki Hakimiyeti",
            path: "/makaleler/fransiz-hakimiyeti",
          },
          {
            key: "asya-direnis-hareketleri",
            title: "Asya'da Direniş Hareketleri",
            path: "/makaleler/asya-direnis-hareketleri",
          },
        ],
      },
      {
        key: "pasifikte-kolonicilik",
        title: "Pasifik'te Kolonicilik",
        path: "/konular/pasifikte-kolonicilik",
        articles: [
          {
            key: "pasifik-hollanda",
            title: "Hollanda'nın Pasifik Politikaları",
            path: "/makaleler/pasifik-hollanda",
          },
          {
            key: "ingiltere-pasifik",
            title: "İngiliz Kolonileri ve Etkileri",
            path: "/makaleler/ingiltere-pasifik",
          },
          {
            key: "fransa-tahiti",
            title: "Fransa'nın Tahiti'yi İşgali",
            path: "/makaleler/fransa-tahiti",
          },
          {
            key: "abd-hawaii",
            title: "ABD'nin Hawaii'yi İlhakı",
            path: "/makaleler/abd-hawaii",
          },
          {
            key: "ispanya-guam",
            title: "İspanya'nın Guam Üzerindeki Hakimiyeti",
            path: "/makaleler/ispanya-guam",
          },
          {
            key: "japonya-pasifik",
            title: "Japonya'nın Pasifik'teki Yayılmacılığı",
            path: "/makaleler/japonya-pasifik",
          },
          {
            key: "avustralya-aborjin",
            title: "Avustralya Aborjin Direnişi",
            path: "/makaleler/avustralya-aborjin",
          },
          {
            key: "deniz-yollari",
            title: "Pasifik'teki Deniz Ticaret Yolları",
            path: "/makaleler/deniz-yollari",
          },
          {
            key: "misyonerlik-pasifik",
            title: "Pasifik'te Misyonerlik Hareketleri",
            path: "/makaleler/misyonerlik-pasifik",
          },
          {
            key: "ticaret-sirketleri",
            title: "Doğu Hindistan Şirketleri ve Pasifik",
            path: "/makaleler/ticaret-sirketleri",
          },
        ],
      },
      {
        key: "afrikada-kolonicilik",
        title: "Afrika'da Kolonicilik",
        path: "/konular/afrikada-kolonicilik",
        articles: [
          {
            key: "berlin-konferansi",
            title: "Berlin Konferansı ve Afrika'nın Bölüşülmesi",
            path: "/makaleler/berlin-konferansi",
          },
          {
            key: "belcika-kongo",
            title: "Belçika'nın Kongo Katliamı",
            path: "/makaleler/belcika-kongo",
          },
          {
            key: "afrika-ingiltere",
            title: "İngiltere'nin Güney Afrika Politikaları",
            path: "/makaleler/afrika-ingiltere",
          },
          {
            key: "fransa-cezayir",
            title: "Fransa'nın Cezayir'deki Sömürge Yönetimi",
            path: "/makaleler/fransa-cezayir",
          },
          {
            key: "afrika-halk-direnisleri",
            title: "Afrika'daki Halk Direnişleri",
            path: "/makaleler/afrika-halk-direnisleri",
          },
          {
            key: "zulu-savasi",
            title: "Zulu Savaşları ve İngilizler",
            path: "/makaleler/zulu-savasi",
          },
          {
            key: "afrika-maden",
            title: "Afrika'daki Maden Sömürüsü",
            path: "/makaleler/afrika-maden",
          },
          {
            key: "afrika-ham-madde",
            title: "Avrupalıların Afrika Hammaddelerine İlgisi",
            path: "/makaleler/afrika-ham-madde",
          },
          {
            key: "osmanli-afrika",
            title: "Osmanlı'nın Afrika'daki Varlığı",
            path: "/makaleler/osmanli-afrika",
          },
          {
            key: "afrika-silah-ticareti",
            title: "Afrika'da Silah Ticareti ve İç Çatışmalar",
            path: "/makaleler/afrika-silah-ticareti",
          },
        ],
      },
      {
        key: "direnisler-ve-isyanlar",
        title: "Direnişler ve İsyanlar",
        path: "/konular/direnisler-ve-isyanlar",
        articles: [
          {
            key: "haiti-devrimi",
            title: "Haiti Devrimi ve Köle Ayaklanmaları",
            path: "/makaleler/haiti-devrimi",
          },
          {
            key: "hint-isyan",
            title: "1857 Hint İsyanı",
            path: "/makaleler/hint-isyan",
          },
          {
            key: "cezayir-direnis",
            title: "Cezayir'deki Direniş Hareketleri",
            path: "/makaleler/cezayir-direnis",
          },
          {
            key: "afrika-koylu-direnisi",
            title: "Afrika'daki Köylü Direnişleri",
            path: "/makaleler/afrika-koylu-direnisi",
          },
          {
            key: "filipinler-direnis",
            title: "Filipinler'de İspanyol Koloniciliğine Direniş",
            path: "/makaleler/filipinler-direnis",
          },
        ],
      },
      {
        key: "dekolonizasyon",
        title: "Dekolonizasyon",
        path: "/konular/dekolonizasyon",
        articles: [
          {
            key: "hindistan-bagimsizlik",
            title: "Hindistan'ın Bağımsızlık Mücadelesi",
            path: "/makaleler/hindistan-bagimsizlik",
          },
          {
            key: "afrika-bagimsizlik",
            title: "Afrika'daki Bağımsızlık Hareketleri",
            path: "/makaleler/afrika-bagimsizlik",
          },
          {
            key: "fransa-cinayeti",
            title: "Fransa'nın Cezayir'deki Katliamları",
            path: "/makaleler/fransa-cinayeti",
          },
        ],
      },
      {
        key: "imparatorluklar",
        title: "İmparatorluklar",
        path: "/konular/imparatorluklar",
        articles: [
          {
            key: "britanya-imparatorlugu",
            title: "Britanya İmparatorluğu ve Küresel Gücü",
            path: "/makaleler/britanya-imparatorlugu",
          },
          {
            key: "fransa-imparatorlugu",
            title: "Fransız Sömürge İmparatorluğu",
            path: "/makaleler/fransa-imparatorlugu",
          },
          {
            key: "hollanda-imparatorlugu",
            title: "Hollanda'nın Sömürge Politikaları",
            path: "/makaleler/hollanda-imparatorlugu",
          },
        ],
      },
    ],
  },
  {
    key: "osmanli",
    title: "Osmanlı İmparatorluğu",
    path: "/osmanli",
    subtopics: [
      {
        key: "asd1",
        title: "Kuruluş Dönemi",
        path: "",
        articles: [],
      },
      {
        key: "asd2",
        title: "Yükseliş Dönemi",
        path: "",
        articles: [],
      },
      {
        key: "asd3",
        title: "Duraklama Dönemi",
        path: "",
        articles: [],
      },
      {
        key: "asd4",
        title: "Gerileme Dönemi",
        path: "",
        articles: [],
      },
      {
        key: "asd5",
        title: "Çöküş Dönemi",
        path: "",
        articles: [],
      },
    ],
  },
];
